- resources/scripts/killer.sh
To be used in the event that  fails for some reason
> chore: add killer script for grep destroying droplets.

- resources/ansible/roles/node/defaults/main.yml
- resources/ansible/roles/node/tasks/main.yml
- src/deploy.rs
- src/main.rs
> feat: set the node RPC to be local by default

- .github/workflows/merge.yml
- resources/ansible/roles/prerequisites/tasks/main.yml
> Revert "fix(ci): wait for DO droplets to finish running cloud-init"

- resources/terraform/logstash/digital-ocean/variables.tf
- resources/terraform/testnet/digital-ocean/variables.tf
> chore: add jason to variables

- .github/workflows/merge.yml
- src/logs.rs
- src/main.rs
- sometimes you'd just want the logs of a specific VM / set of VMs. This is a useful one to have.
> feat: filter the vms to rsync from

- resources/scripts/upload-random-data.sh
- writes the metrics about the uploader to a `uploader_metrics.csv`
- If there is an error during upload, we just write the time & file size to the CSV
- writes stdout to `uploader.log`
> feat(uploader): collect uploader metrics into a csv file

- src/ansible/provisioning.rs
- src/lib.rs
- src/main.rs
This can also be useful for the upgrade process.
> feat: custom inventory for upgrade-node-manager cmd

- src/lib.rs
For an unknown reason, when it comes back from S3, the environment type file is sometimes empty, or it has a newline character.
Here we try to get rid of the newline, and if the file is empty, fallback to using the name of the environment to determine the type.
> fix: try to ensure environment type value

- resources/terraform/testnet/digital-ocean/production.tfvars
The creation of this VM came from a request from Qi. The environment has already been upscaled using the `Upscale` workflow, so I'm matching the count in the tfvars file.
> chore: increase production auditor count

- resources/ansible/upgrade_uploaders.yml
- src/ansible/mod.rs
- src/main.rs
Upgrades the uploaders to the latest version of the `safe` client.
> feat: provide `upgrade uploaders` command

- resources/ansible/roles/uploaders/files/upload-random-data.sh
This was requested for the chunk/node size experiments.
> chore: remove sleep from uploader

- resources/terraform/testnet/digital-ocean/variables.tf
This was mistakenly not provided in the previous pull request.
> chore: include variable definition

- resources/ansible/roles/uploaders/files/upload-random-data.sh
We could run this as a cron, but it's easy enough to just have it in the uploader; it should be a fast operation if it runs regularly.
> feat: prune old chunk artifacts

- resources/ansible/start_uploaders.yml
- resources/ansible/stop_uploaders.yml
These services were recently changed to be templated.
> feat: start and stop all uploader services

- resources/terraform/testnet/digital-ocean/production.tfvars
Droplet sizes are increased as agreed.
> chore: new production specifications

- resources/terraform/testnet/digital-ocean/dev.tfvars
The increased chunk size requires larger machines.
> chore: increase sizes of dev machines

- src/inventory.rs
The `safenode-manager` and `autonomi` versions are retrieved from a previous deployment by connecting to a node and uploader VM, respectively.
Retrieving these versions now results in the upscale working correctly for EVM-based networks.
> feat: use ssh to retrieve binary versions

- resources/terraform/testnet/digital-ocean/dev.tfvars
We can use single VMs for these.
> chore: reduce bootstrap and uploaders for dev spec

- src/upscale.rs
A couple of variables were not being set correctly.
> fix: bring plan inline with the apply

- src/lib.rs
The code was previously assuming we could obtain the multiaddr from the first node in the list, but I encountered a situation where the first node in the list was one of the new nodes I was trying to bring online, which doesn't work for selecting an existing multiaddr.
> fix: correctly select node for obtaining multiaddr

- src/main.rs
The `upscale` command can now support supplying different version for `safenode` and `safenode-manager`. This is useful to prevent having to do an upgrade on new machines that come online.
> feat: provide safenode and safenode-manager overrides

- resources/ansible/nodes.yml
- resources/ansible/roles/telegraf-configuration/tasks/main.yml
- resources/ansible/roles/uploader-metrics/defaults/main.yml
- resources/ansible/roles/uploader-metrics/tasks/main.yml
- src/lib.rs
This also re-enables the automatic start for Telegraf.
> chore: use new names for telegraf config files

- resources/terraform/testnet/digital-ocean/PROD-01.tfvars
This was the spec discussed and agreed for the next production environment.
> chore: specification for prod-01

- resources/terraform/testnet/digital-ocean/variables.tf
This should not have been merged into the RC branch.
> chore: set default volume size if node count is not provided

- src/lib.rs
This is useful when doing upscaling just to check all nodes are running after the upscale.
> feat: extend `status` command with a summary

- src/upscale.rs
The provisioning process had moved along a little bit since the last time we had performed an upscale of the uploaders, but it's working now.
I tested both upscaling the VMs and the uploaders per machine.
> feat: re-enable upscaling for uploaders

- resources/ansible/roles/private_node/tasks/main.yml
- Adjust workflow to support upscaling of private nodes in the proper sequence
Please mark the types of changes made in this pull request.
Please ensure all of the following tasks have been completed:
> fix: allow scaling of private nodes in DO environment

- src/ansible/extra_vars.rs
- src/ansible/provisioning.rs
- Builds the `evm-testnet` binary from the specified branch.
> fix: build evm testnet from the provided branch

- src/ansible/inventory.rs
- src/error.rs
- src/logs.rs
- src/ssh.rs
- Adds support to rsync logs from both full cone and symmetric private nodes.
> fix(logs): support rsync of logs for private nodes

- src/ansible/extra_vars.rs
- src/cmd/mod.rs
- src/cmd/provision.rs
- 8a82026 **feat: provision downloaders on the `provision clients` cmd**
If the downloaders are enabled, they get provisioned along with the clients.
- 2e78a4b **chore: tidy arguments and documentation**
> feat: provision downloaders on the `provision clients` cmd

- src/inventory.rs
- reduces the time taken from ~4 mins to 1 min on a small testnet.
> feat: fetch inventories in parallel using std threads

- resources/ansible/roles/downloaders/templates/ant_performance_verifier.service.j2
- resources/ansible/roles/node/tasks/main.yml
- src/ansible/extra_vars.rs
- src/ansible/provisioning.rs
- src/bootstrap.rs
- src/clients.rs
- src/cmd/clients.rs
- src/cmd/deployments.rs
- src/cmd/mod.rs
- src/deploy.rs
- src/lib.rs
- src/main.rs
- Useful to re-run a failed deployment without compiling the binaries
again.
> feat: introduce arg to not rebuild binaries
