.gitignore, Cargo.lock, Cargo.toml, resources/ansible/ansible.cfg, resources/ansible/logs.yml, resources/ansible/roles/log_forwarding/templates/logstash.conf.j2, resources/ansible/roles/node/templates/sn_node.service.j2, resources/scripts/reorganise_logs.py, resources/terraform/digital-ocean/variables.tf, src/error.rs, src/lib.rs, src/logs.rs, src/main.rs, src/s3.rs, src/tests/build_safe_network_binaries.rs, src/tests/clean.rs, src/tests/init.rs, src/tests/provision_faucet.rs, src/tests/provision_genesis_node.rs, src/tests/provision_remaining_nodes.rs, src/tests/setup.rs
- d526a54 **feat: provide log retrieval commands**
Log retrieval has two components: obtaining the files from S3 and reassembling them. There is a
separate subcommand for each.
Obtaining the files is a recursive process that involves visiting the hierarchy of folders in the
bucket. Since there are lots of folders, this can be time consuming for a large testnet.
Logstash is forwarding the files to the bucket in parts, every 30 minutes. For this reason, they
need to be reassembled back into a single file. This is based on the part numbers in the file names.
The use of different GUIDs on each file part is done intentionally by Logstash.
The reason these have been implemented as separate subcommands is so that we can continually sync
the logs from S3 if that is necessary, without …
=> feat: provide log retrieval commands

README.md, src/ansible.rs, src/error.rs, src/lib.rs, src/main.rs, src/tests/clean.rs
The tool would not run correctly in a GHA workflow, which needed some extra debugging information and changes:
* Call `terraform init` on the `clean` command. In a GHA workflow you can't assume that Terraform has already been initialised. This would also facilitate a clean from your dev machine rather than using the GHA workflow, if you done that.
* Only attempt to remove inventory files if they exist. They don't exist in the GHA destroy workflow.
* Run the `init` command when using `logs copy`. This may be necessary if you've launched your testnet using the GHA workflow but you want to obtain the logs on your dev machine. In this case, the inventory needs to be created.
=> chore: add debugging output

src/error.rs, src/lib.rs, src/main.rs, src/manage_test_data.rs, src/setup.rs
Sends a notification to Slack, which is populated by details from the deployment inventory for the testnet. It's based on supplying an incoming webhook URL, which is a secret value.
Rather than send in a notification for every testnet that goes up, the user needs to explicitly run the command to send it in. A lot of experimental testnets won't be of interest to everyone.
=> feat: provide `notify` command

src/error.rs, src/main.rs, src/s3.rs
Example error output with this change:
```
$ cargo run -- deploy --name beta
Error: 
0: Failed to list objects in S3 bucket with prefix 'testnet-logs/beta/': The AWS Access Key Id you provided does not exist in our records.
```
=> feat: report error message as part of Error::ListS3ObjectsError

resources/ansible/build.yml, src/error.rs, src/lib.rs, src/main.rs, src/manage_test_data.rs, src/safe.rs, src/tests/build_safe_network_binaries.rs, src/tests/provision_genesis_node.rs, src/tests/provision_remaining_nodes.rs, src/tests/setup.rs, src/tests/upload_test_data.rs
Optionally supply version numbers, which will deploy the binaries built during the release process. We still need to build the faucet binary because that's not a released artifact at the moment.
When the version number arguments are used, we skip building the `safenode` and `safe` binaries, which does shave a decent amount of time off the overall process.
The other significant difference is that we pull the version binaries from the Github release rather than S3, so we had to introduce another mechanism for downloading those. At the moment the release process does not include uploading the versioned binaries to S3. Only the 'latest' version goes up there.
=> feat: deploy using version numbers for binaries

resources/packer/build.pkr.hcl, resources/terraform/testnet/digital-ocean/variables.tf
A new image was generated for the build machine with the newest version of Rust on it. The Rust installation is not applied during the provisioning process. It's installed along with some other prerequisites in an attempt to save time in the deploy process.
The version of Ubuntu that the build machine was using is actually no longer available, so I changed it to a slightly earlier version. I tried a later one, but Ansible wouldn't install on it.
The node image was also regenerated here because I thought it also had a Rust installation on it, but it actually doesn't. It doesn't really do any harm to just generate a new version anyway.
=> chore: upgrade build and node images

resources/ansible/roles/safenode_rpc_client/templates/safenode_rpc_client.service.j2
Depends on https://github.com/maidsafe/safe_network/pull/1045
=> chore: adapt to new safenode-rpc-client and use royalties beneficiary PK instead of SK

Cargo.lock, Cargo.toml, resources/ansible/roles/node/tasks/main.yml, src/ansible.rs, src/deploy.rs, src/lib.rs, src/logstash.rs, src/main.rs
- 401beb6 **chore: require arg for verbose ansible output**
I find the verbose output in Ansible to be a bit excessive for most situations, though it can
definitely be useful for debugging. This small change uses a flag to tell it to be more verbose.
- 88277a9 **chore: use minimal verbosity on node manager**
These node manager commands can produce lots of output, which makes it difficult to read if the run
fails. Using one `-v` makes the manager output in a more minimal style, making the failures easier
to read.
- 12f1c8e **chore: remaining node failure will not end deploy**
Most of the time, the errors we are seeing on the provision of the remaining nodes is because one or
two nodes, out of something like forty, will randomly fail to start. Previously this was causing the
whole deploy to …
=> chore: remaining node failure will not end deploy

resources/ansible/faucet.yml, resources/ansible/logstash.yml, resources/ansible/safenode_rpc_client.yml
These should also have been removed because they are also no longer required.
=> chore: remove additional prerequisite roles

Cargo.lock, src/deploy.rs
The override was applied to the wrong variable, which caused `safenode` to be overwritten with `safenodemand`.
=> fix: override correct variable

Cargo.lock, Cargo.toml, src/lib.rs, src/main.rs, src/network_commands.rs
The [PR from sn](https://github.com/maidsafe/safe_network/pull/1448/) has to be published before this PR can turn green.
=> feat(script): add scripts to interact with a running testnets

src/lib.rs, src/main.rs, src/network_commands.rs
Depends on https://github.com/maidsafe/sn-testnet-deploy/pull/93
=> feat(network): perform random interval network churns

src/ansible.rs
When no variables are specified, just return an empty document. Not doing so caused an error on the `unwrap` call shortly after.
=> fix: empty json document for no vars

Cargo.lock, Cargo.toml, src/ansible.rs, src/lib.rs, src/main.rs, src/manage_test_data.rs
- 513773c **chore: alphabetically arrange cmds and args**
In my opinion, when you have so many commands and arguments, the best way to keep them tidy is to
arrange them alphabetically. The `clap` crate that provides the CLI will indicate which of the
arguments are mandatory, and if the user needs more information on the mandatory arguments, they can
consult the list alphabetically.
Also just tidied the documentation on some of the arguments.
- d68cb8e **chore: use version/branch arguments differently**
To make things easier to manage, I've changed argument usage with respect to versioning and building
binaries: you either use versions or you build all the binaries.
In the case of building the binaries, things are as they were before: you need to supply the branch
and repo owner at the …
=> feat: provide `--safenode-manager-version` arg

resources/ansible/upgrade_node_manager.yml, src/lib.rs, src/main.rs
Simple mechanism for upgrading the node manager binaries. It connects to each machine and downloads the given version of the binary, then overwrites the existing copy. This should be all we need for now.
=> feat: provide `upgrade-node-manager` command

resources/ansible/start_nodes.yml, src/lib.rs, src/main.rs
This will execute a simple playbook that will use the node manager to start all the nodes on the machine.
This can be useful if some nodes didn't start up properly after being upgraded.
=> feat: provide `start` command

resources/ansible/roles/build_safe_network_binary/tasks/main.yml, src/ansible.rs, src/deploy.rs, src/error.rs, src/inventory.rs, src/lib.rs, src/logs.rs, src/logstash.rs, src/main.rs, src/manage_test_data.rs, src/network_commands.rs, src/rpc_client.rs, src/s3.rs, src/terraform.rs
- 2cbf1de **chore: remove terraform check on `inventory` cmd**
It shouldn't be necessary to have an initialised Terraform workspace to get the inventory for
deployment, which is the case when using a GHA workflow.
- 819abb5 **refactor: narrow binary option for deployment**
We previously had an `SnCodebaseType` enum with three variants: `Main`, `Branch` and `Versioned`.
Now that we can use the release repository to retrieve the latest versions for binaries, I didn't
see the necessity for a third option; we simply use a version or we build from source. With that in
mind, I renamed the enum to `BinaryOption` and provided `BuildFromSource` and `Versioned` variants.
I don't think there should be any functional change here.
- 08e1d4f **refactor: introduce `inventory` module**
I was finding the …
=> Inventory Enhancements and Reorganisation

src/ansible.rs
The check only applied to a relative path, which is not necessary relative to the current working directory. Using the full path resolves the problem.
=> fix: provide full inventory path

src/error.rs, src/inventory.rs, src/main.rs, src/s3.rs
When a deployment completes, the network contacts will automatically be uploaded to S3. By default, the file will have the same name as the environment, but an optional argument allows it to be specified.
During the deployment, it's possible that some nodes don't start. These are indicated by "-" entries in the peer list. The process ensures they will not be added to the contacts list.
=> feat: upload network contacts to s3

resources/ansible/roles/auditor/tasks/main.yml
It looks like at some point, the name of the auditor binary changed from `sn_auditor` to `auditor`, which broke the idempotency for the deployment.
=> fix: use correct reference to auditor binary

resources/ansible/roles/auditor/defaults/main.yml, src/deploy.rs, src/main.rs
A secret key can optionally be supplied, but otherwise, a default will be used. The default is moved out of Ansible and into the `testnet-deploy` binary. This is being provided to support supplying a key for the initial beta launch.
A Clippy warning related to a large enum variant was suppressed. There are quite a lot of arguments for the tool, but it doesn't seem like it's something problematic.
=> feat: provide `--beta-encryption-key` arg on `deploy` cmd

resources/ansible/roles/node/tasks/main.yml
this means maidsafe nodes will forward on rewards
handily avoiding accumulating 61422 on a public node (which could be an attack vector)
=> feat: set node owner

resources/packer/node/node.pkr.hcl, resources/terraform/testnet/digital-ocean/variables.tf
So we can determine bootstrap node requirements reliably
=> feat: increase base node size

resources/ansible/roles/node/tasks/main.yml, src/inventory.rs
Ensure that we count at least one node to add, otherwise rpc port calculation is off and we dont add any
=> fix: dont try to find audit ip if no inventory

src/deploy.rs, src/inventory.rs, src/lib.rs, src/logs.rs, src/main.rs
The `TestnetDeploy` struct is also renamed to `TestnetDeployer`, which is a better indicator that this struct contains behaviour rather than just state.
The `DeployCmd` is renamed to `DeployOptions`, and the behaviour for executing the deployment is moved back into `TestnetDeployer`. We still define the `deploy` function in a separate file, which is worth it because there is quite a lot of code. We can take advantage of the fact that Rust allows us to implement the behaviour of a struct across multiple files.
The reason for the refactor is because I always found it a bit odd that a large object like `TestnetDeployer` was being passed into a command object. In most situations, commands are objects that only have state, providing the parameters for some operation that is generally performed …
=> refactor: `DeployCmd` -> `DeployOptions`

resources/ansible/roles/metrics/tasks/main.yml, resources/terraform/testnet/digital-ocean/main.tf, resources/terraform/testnet/digital-ocean/variables.tf, src/ansible.rs, src/deploy.rs, src/inventory.rs, src/lib.rs, src/main.rs, src/manage_test_data.rs
- 9ad4ba3 **feat: merge bootstrap and 'normal' nodes into one environment**
Terraform now deploys two different types of nodes: bootstrap and 'normal', where the former are
a set of larger machines that are used for an initial bootstrap. Being deployed as two different
types means they can be scaled independently, and this can be controlled by two arguments on the
`deploy` command: `--bootstrap-node-vm-count` and `--node-vm-count`.
Merging the nodes into one environment also removes the need for the `--bootstrap-peer` argument. If
we want to extend our deployment with more machines of either type, we can run the `deploy` command
again with updated values for the node counts, and any peers we need will already be in the
inventory.
Two aspects of inventory management were also changed. …
=> feat: merge bootstrap and 'normal' nodes into one environment

src/main.rs
This was the count used in the recent production deployment and it's also the value that's stated in the workflow documentation.
=> chore: use 25 as default node count

src/ansible.rs, src/lib.rs, src/logstash.rs, src/main.rs
Provide the ability to set the forks value for Ansible on the `deploy` command. Previously it was only available on the upgrade command.
=> feat: configure ansible forks on deploy

src/error.rs, src/lib.rs, src/logs.rs, src/main.rs, src/ssh.rs
- Use common timestamp per rg run.
- Do not print error if no matches are found.
- write the rg command that was used inisde the output file.
=> chore(logs): use common timestamp for all rg files

Cargo.lock, resources/ansible/node_manager_inventory.yml, resources/ansible/upgrade_nodes.yml, src/ansible/provisioning.rs, src/inventory.rs, src/lib.rs, src/main.rs
- 5204a49 **feat: provide `--interval` arg for `upgrade` cmd**
The `upgrade` command on the node manager already has an `--interval` argument, but it wasn't
controllable from `testnet-deploy`. The default value used by the node manager is only 200ms, which
has been observed to be problematic in some cases.
Also fix a little bug that caused `testnet_deploy` to be incorrectly initialised.
- 36f050e **feat: `upgrade` cmd purposed for use in workflow**
The `upgrade` command was originally written to run from a dev environment, which assumes the
existence of an initialised Terraform workspace. An upgrade doesn't require a Terraform run, but the
Terraform workspace was being used to check for the existence of the environment specified. This
check is now performed using the deployment inventory. …
=> Various Features for Supporting New Workflows

resources/ansible/roles/node/tasks/main.yml
- Safenode manager now caries out the same validation steps for all the ports passed to it.
- Earlier, only `node-port` was validated, thus this went unnoticed.
=> chore: set the correct end port

resources/ansible/ansible.cfg, resources/ansible/node_status.yml, resources/ansible/roles/metrics/tasks/main.yml, resources/ansible/stop_telegraf.yml, resources/ansible/upgrade_telegraf_config.yml, src/ansible/mod.rs, src/ansible/provisioning.rs, src/lib.rs, src/main.rs
- 5f23b97 **feat: provide `stop-telegraf` command**
The Telegraf service is currently using `safenode-manager status`, which causes the registry file to
be re-written. This could interfere with an upgrade process.
A longer term solution would be to provide some kind of status command which is read only.
- 42076f0 **chore: increase ansible timeout**
During the production upgrade process we were seeing a lot of failed connection attempts. Going to
see if increasing the timeout will make any difference.
- 978b36b **feat: extend `status` command to run `safenode-manager status`**
Adding this in means the command can run at any point in time and the current state will be
obtained, not the state when the node manager last ran.
- c7ccbb1 **feat: more reliable ssh configuration**
Increase the …
=> Various Changes for Telegraf and Upgrades

resources/ansible/roles/node/tasks/main.yml
- we are currently setting a port range even if we're starting a single node, i.e,. `13000-13000`. This fails with the latest version of safenode-manager
=> fix: do not use port range for a single node

Justfile, resources/packer/node/node.pkr.hcl, resources/terraform/testnet/digital-ocean/dev.tfvars, resources/terraform/testnet/digital-ocean/main.tf, resources/terraform/testnet/digital-ocean/production.tfvars, resources/terraform/testnet/digital-ocean/staging.tfvars, resources/terraform/testnet/digital-ocean/variables.tf, src/deploy.rs, src/error.rs, src/inventory.rs, src/lib.rs, src/logstash.rs, src/main.rs, src/s3.rs, src/terraform.rs, src/upscale.rs
An `EnvironmentType` enum is introduced, with three variants: `Development`, `Staging`, and
`Production`. The intention is for the network being deployed to have a specification that resembles
either of these three possibilities. The variant determines the number of droplets, their size, and
image IDs, and the number of node services on each VM. These values are stored in `tfvars` files
that correspond to each of the variants.
The environment type selection is persisted in the deployment inventory by storing it in a file in a
new S3 bucket. This is used so that the correct tfvars file gets used during upscale operations.
Without this, there would be a risk that droplet sizes could change, which would cause droplets to
be recreated. The file is deleted when the deployment is cleaned. For …
=> feat: vary machine sizes and counts for environment types

.github/workflows/release.yml, .github/workflows/version_bump.yml, .gitignore, Cargo.toml, Justfile, release-plz.toml
The process here is copied from one of our other non-workspace repositories. It is slightly different here in that we only need to produce a binary for Linux, but otherwise it is the same.
The testnet tool also needs access to the Terraform and Ansible definitions, so it doesn't work as a binary in isolation. We can add a second step to somehow distribute these files along with it. For now, a tag of the repository can be checked out along with the binary.
=> chore: introduce release process

resources/ansible/ansible.cfg, resources/ansible/callback_plugins/show_hosts.py
Increase the timeout values to 10 minutes and specify a fairly small keep-alive interval.
Even though Ansible reports 'UNREACHABLE', I have managed to confirm that a connection does actually take place. The status of the node manager's registry was misleading me to believe no connection was established. The node manager does not update the registry for every node that is upgraded; it only updates it at the end of the whole operation. So, if it gets cut off, the registry makes it look like no nodes have changed version. I was able to confirm that they did change version, by running `safenode --version` for several of the individual binaries.
I am therefore trying a larger timeout, and trying to keep the connection alive by sending packets every 10 seconds.
The plugin for showing the host …
=> chore: try other ssh options

resources/ansible/start_telegraf.yml, src/ansible/mod.rs, src/ansible/provisioning.rs, src/lib.rs, src/main.rs
- f4b8b12 **feat: provide `start-telegraf` command**
Restarts the Telegraf service across a deployment.
We provide this so we can restart Telegraf services that were stopped for the upgrade. There is
another command for upgrading the Telegraf configuration, which also starts the service, but
sometimes it's not appropriate to deploy a new configuration.
- f710cd0 **feat: custom inventory for telegraf commands**
This can also be useful for the upgrade process.
=> feat: provide `start-telegraf` command

src/ansible/provisioning.rs, src/inventory.rs, src/lib.rs
Sometimes, particularly on the production environment, the retrieval of node registries can fail. The suspicion is that it's because Telegraf is in the process of writing to the file, and therefore the file is incomplete, but, it's not completely clear.
Now we take the failure into account and return a list of the VMs for which we couldn't retrieve registries.
=> feat: take failure into account for node registry retrieval

resources/ansible/node_manager_inventory.yml, resources/ansible/roles/node/tasks/main.yml, resources/terraform/testnet/digital-ocean/dev.tfvars, resources/terraform/testnet/digital-ocean/main.tf, resources/terraform/testnet/digital-ocean/production.tfvars, resources/terraform/testnet/digital-ocean/staging.tfvars, resources/terraform/testnet/digital-ocean/variables.tf, src/ansible/provisioning.rs, src/deploy.rs, src/error.rs, src/inventory.rs, src/lib.rs, src/main.rs, src/terraform.rs, src/upscale.rs
- 1a2af2c **feat: take failure into account for node registry retrieval**
Sometimes, particularly on the production environment, the retrieval of node registries can fail.
The suspicion is that it's because Telegraf is in the process of writing to the file, and therefore
the file is incomplete, but, it's not completely clear. It seems to fail too often for that to be
the case.
Now we take the failure into account and return a list of the VMs for which we couldn't retrieve
registries.
- 572e2d7 **fix: set use_port_range to default value**
On subsequent playbook runs where no new nodes are being added, not setting this to a default value
causes the later node manager task to fail, because it evaluates which arguments to use based on
this setting.
- 424db79 **fix: do not error if node man …
=> feat: include the auditor in the `upscale` command

resources/terraform/testnet/digital-ocean/production.tfvars
These new settings are based on analysis of the metrics we are collecting.
The specifications for generic nodes are retained. For bootstrap nodes, they are downsized to 4xCPU and 8GB of memory. The estimated cost reduction here is from $6400 to $2400 per month. On both types, the number of node services will remain the same.
The auditor count is reset to 1 for the new environment.
=> chore: redefine specs for new production environment

resources/ansible/roles/uploaders/tasks/main.yml, resources/ansible/roles/uploaders/templates/safe_uploader.service.j2, resources/ansible/start_uploaders.yml, resources/ansible/stop_uploaders.yml, resources/terraform/testnet/digital-ocean/production.tfvars, src/ansible/mod.rs, src/main.rs
- 53771f6 **refactor: run uploaders in a service**
Rather than using `nohup` to run the uploader script in the background, we can easily wrap it in a
systemd service, which makes it easy to control the uploaders.
- 5710238 **chore: reapply new production specs**
We have decided to go with the release, and the `PROD-01` auditor was provided.
- 45cab47 **feat: provide commands for controlling uploaders**
These two commands can be used by workflows for starting and stopping the uploaders for a given
environment.
=> feat: provide commands for controlling uploaders

resources/ansible/start_faucet.yml, resources/ansible/stop_faucet.yml, src/ansible/mod.rs, src/main.rs
These two commands can be used by workflows for starting and stopping the faucet for a given environment.
=> feat: provide commands for controlling the faucet

resources/ansible/fund_uploaders.yml, src/ansible/mod.rs, src/inventory.rs, src/main.rs
This is a tedious manual chore that can easily be done automatically.
The command relies on the faucet being started, so that command has to be used first.
=> feat: provide `fund-uploaders` command

resources/ansible/roles/uploader-metrics/tasks/main.yml, resources/ansible/upgrade_node_telegraf_config.yml, resources/ansible/upgrade_uploader_telegraf_config.yml, src/ansible/mod.rs, src/ansible/provisioning.rs, src/lib.rs, src/main.rs
- 14b5b0c **refactor: rename upgrade telegraf command**
We will now have two different commands for upgrading the Telegraf configurations, one for the node
configuration and the other for uploaders.
- b6b3cec **feat: provide an `upgrade-uploader-telegraf-config` cmd**
This is almost identical to the other Telegraf command.
=> feat: provide an `upgrade-uploader-telegraf-config` cmd

resources/ansible/roles/build_safe_network_binary/tasks/main.yml, resources/terraform/testnet/digital-ocean/main.tf, resources/terraform/testnet/digital-ocean/variables.tf, src/ansible/extra_vars.rs, src/ansible/provisioning.rs, src/bootstrap.rs, src/deploy.rs, src/error.rs, src/inventory.rs, src/lib.rs, src/main.rs, src/manage_test_data.rs, src/upscale.rs
- b7abcff **refactor: make some version numbers optional**
To setup a command that will deploy a new set of nodes that are bootstrapped from an existing
deployment, the auditor, faucet and safe versions will be set to optional.
The bootstrapped deployment will just supply some extra nodes, so it won't have a genesis node, a
faucet, an auditor, or any uploaders.
- 0f867d7 **feat: extend deployment inventory with deployment type**
The inventory for a deployment now stores the type of the deployment, in addition to the environment
type.
The deployment type is either `New` or `Bootstrap`, where the latter is a deployment that bootstraps
from one of the peers in an existing deployment. In the bootstrap deployment, there will be no
genesis, bootstrap, uploader or auditor VMs.
- 88fb100 **feat: …
=> feat: provide `bootstrap` command

resources/ansible/roles/build_safe_network_binary/tasks/main.yml, src/ansible/provisioning.rs, src/deploy.rs, src/main.rs, src/upscale.rs
This is necessary for the chunk size experiments.
The value will be passed to the role that builds binaries.
=> feat: provide `chunk-size` argument on the `deploy` cmd

Justfile, resources/packer/node/node.pkr.hcl, resources/scripts/install_ansible.sh, resources/terraform/testnet/digital-ocean/main.tf, resources/terraform/testnet/digital-ocean/production.tfvars
Using the bootstrap image did not work for the production configuration because the prod bootstrap image is larger than the size of the machine we are trying to create for the gateway.
Had to change the Ubuntu version because it seems that Digital Ocean have now pulled the version we were using. Also had to add some extra retries into the Ansible installation script to get the image to build properly.
=> chore: create nat gateway image for prod

src/ansible/inventory.rs
The private inventory file required host key checking to be explicitly disabled, otherwise it prompts for user input when trying to establish a connection to the gateway VM.
=> fix: disable host key checking in private inventory

resources/terraform/testnet/digital-ocean/dev.tfvars, resources/terraform/testnet/digital-ocean/staging.tfvars, src/ansible/extra_vars.rs, src/ansible/provisioning.rs, src/main.rs, src/upscale.rs
Since we don't record the versioning information that was used with the initial deployment, if we are going to upscale the uploaders, we need to supply the version we want to use for the `safe` binary.
This is a simple solution for now. In the future we could record the binary information in the environment information that is on S3.
=> feat: provide `--safe-version` arg for `upscale` cmd

resources/ansible/configure_swapfile.yml, src/ansible/mod.rs, src/main.rs
We now have a requirement to setup a swapfile on all the node machines.
There is also an option to run against the bootstrap nodes.
=> feat: provide `configure-swapfile` command

resources/ansible/genesis_node.yml, resources/ansible/roles/genesis-node/defaults/main.yml, resources/ansible/roles/genesis-node/tasks/main.yml, resources/ansible/roles/node/defaults/main.yml, resources/ansible/roles/node/tasks/main.yml, src/ansible/extra_vars.rs, src/ansible/provisioning.rs, src/bootstrap.rs, src/deploy.rs, src/lib.rs, src/upscale.rs
- 3102499 **refactor: split node role into two**
A `genesis-node` role is extracted from the `node` role. This avoids the need for having genesis
conditionals on the other tasks in the `node` role, making things easier to understand. This will be
important for the EVM-based network, where even more arguments for `safenode-manager` will be
introduced.
- 9955fde **refactor: move extra vars functions to module**
These functions were cluttering the `provisioning` module. They can be grouped along with
other extra vars functions in the `extra_vars` module.
- 4027883 **refactor: remove duplicate `NodeType` struct**
This struct had been duplicated, so one of them was deleted and the other was moved to sit alongside
the other enums in the main `lib` module.
- a835236 **chore: remove redundant …
=> refactor: split node role into two

resources/ansible/build.yml, resources/ansible/roles/uploaders/defaults/main.yml, resources/ansible/roles/uploaders/files/upload-random-data.sh, resources/ansible/roles/uploaders/tasks/main.yml, resources/ansible/roles/uploaders/templates/autonomi_uploader.service.j2, src/ansible/extra_vars.rs, src/ansible/provisioning.rs, src/deploy.rs, src/lib.rs, src/main.rs, src/upscale.rs
- 97ada2d **fix: replace autonomi cli references**
The binary was renamed to `autonomi` rather than `autonomi_cli`.
- 70e58db **feat: extend `deploy` command to use arbitrum sepolia**
In this setup, there may be some issues with using one wallet for multiple uploaders, but this
should get us started.
=> feat: extend `deploy` command to use arbitrum sepolia

resources/ansible/roles/uploaders/defaults/main.yml, src/ansible/extra_vars.rs
The new binary does not get uploaded here. This was only noticed now because it's the first time I've tried to deploy a versioned `autonomi`.
The default URL was also removed. There isn't a 'latest' version of this binary available anyway. The URL always needs to be passed.
=> chore: replace old `sn-cli` bucket ref

Cargo.lock, Cargo.toml, resources/ansible/upgrade_uploaders.yml, src/ansible/extra_vars.rs, src/ansible/provisioning.rs, src/inventory.rs, src/lib.rs, src/main.rs, src/upscale.rs
- 70bc28c **feat: obtain listener addresses with quic protocol**
We have now added the `websockets` feature to `safenode`, and this means it exposes `ws` listener
addresses. We are only interested in the `quic-v1` addresses.
- 28438fa **feat: replace safe bin with autonomi**
The `sn_releases` reference is updated to the latest version, which replaces the `ReleaseType::Safe`
variant with `ReleaseType::Autonomi`, which will ensure the correct version of the client is
obtained.
The commit also removes other traces of the faucet that are no longer necessary. The
`ReleaseType::Faucet` variant was removed from the latest version of `sn_releases`.
=> feat: obtain listener addresses with quic protocol

Cargo.lock, Cargo.toml, resources/ansible/roles/uploaders/tasks/main.yml, resources/ansible/roles/uploaders/templates/autonomi_uploader.service.j2, resources/ansible/start_uploaders.yml, resources/ansible/stop_uploaders.yml, src/ansible/extra_vars.rs, src/ansible/inventory.rs, src/ansible/provisioning.rs, src/deploy.rs, src/error.rs, src/funding.rs, src/lib.rs, src/main.rs, src/upscale.rs
- During deployment & upscale:
- The funds from `funding_wallet_sk` will be sent to all the uploaders. Currently set to 1 token & 0.1 ETH gas for each uploader.
- The SK from the anvil node will be used as `funding_wallet_sk` in case of a Custom network
- If we miss any uploader services, a key will be generated for them and funds will be sent to them as well.
- Those missing services will then be provisioned. 
- During `Fund` command
- funds will be sent to all the SKs that are defined inside the service definition file
=> feat: use separate wallets for each uploader

resources/terraform/testnet/digital-ocean/production.tfvars
The other type is not available in our region.
=> chore: use `intel` type for prod droplets

resources/terraform/testnet/digital-ocean/production.tfvars
We used custom node sizes in the deployment, so this brings them in line.
=> chore: align prod specs with environment

resources/ansible/roles/uploaders/files/upload-random-data.sh, src/ansible/provisioning.rs, src/error.rs, src/funding.rs, src/main.rs, src/upscale.rs
This upscales the uploaders on their own, as opposed to upscaling all the components of the network.
We also change the size of uploaded files from 15 to 150MB.
=> feat: provide `uploaders upscale` command

resources/ansible/roles/uploaders/files/upload-random-data.sh
Yesterday we increased this to 150mb to get some more data flowing through the production network, but it contributed to a development comparison filling up its disk space quite quickly.
For now we will revert back to 15, but shortly we can make it a configurable value.
=> chore: revert upload file size to 15mb

resources/ansible/stop_nodes.yml, src/ansible/extra_vars.rs, src/ansible/mod.rs, src/ansible/provisioning.rs, src/bootstrap.rs, src/deploy.rs, src/error.rs, src/inventory.rs, src/lib.rs, src/main.rs, src/upscale.rs
- stop all running nodes with `--interval` option. Depends on the safenode-manager upgraded to use this commit https://github.com/maidsafe/safe_network/pull/2385
- stop/start nodes or telegraph on specific node types.
- upgrade safenode/safenode-manager on speicifc node types
=> feat: introduce cmd to stop all running nodes

resources/ansible/upgrade_nodes.yml, src/lib.rs, src/main.rs
The `upgrade` command can use this delay when there is only one node per machine. Bootstrap nodes can typically be deployed like this.
Without this, even using one fork, there would be no delay between servicing each machine in the inventory.
=> feat: provide `--pre-upgrade-delay` arg

resources/ansible/start_telegraf.yml, src/inventory.rs, src/main.rs
Now that we have websockets enabled, there is an interest in finding listener addresses that are not using QUIC.
We now store all the listener addresses, and we can filter them when reporting. The `inventory` command adds an optional `full` flag that will print the whole list, grouped by QUIC and websockets.
For some reason there was a filter applied to the printing of peers with respect to a bootstrap deployment. That was removed. I can't think why I added it in the first place; it would be useful to print the peers even if the deployment is a bootstrap type.
=> feat: capture all listener addresses in inventory

resources/ansible/stop_nodes.yml, src/ansible/provisioning.rs, src/inventory.rs, src/lib.rs, src/main.rs
- 55bd63e **chore: order bootstrap peers by vm name**
- f450d3b **feat: provide `delay` for `start` command**
Similar to the `upgrade` command, this can be used when we want to stop nodes when there is only one
running on each machine.
=> feat: provide `delay` for `start` command

resources/ansible/update_peer.yml, src/ansible/inventory.rs, src/ansible/mod.rs, src/main.rs
This command can be useful as a quick way to update the peer reference in the node registry. This in turn will cause the service definitions to be updated when they are upgraded.
=> feat: provide `update-peer` command

src/upscale.rs
The upscale is not working for EVM-based payments because the wallet secret key is missing.
I'm not sure exactly how we will adapt this.
=> chore: disable upscale for uploaders

resources/ansible/roles/uploaders/files/upload-random-data.sh, resources/ansible/roles/uploaders/tasks/main.yml, resources/ansible/roles/uploaders/templates/autonomi_uploader.service.j2, resources/ansible/roles/uploaders/templates/upload-random-data.sh.j2, resources/ansible/upgrade_uploaders.yml, src/main.rs
- 34a2f9c **feat: use inifinite loop in uploader script**
There is no reason to upload some finite number of files; we just want the uploader to run forever.
Also removes the chunk artifact pruning; this is not something we need with the new `autonomi`
client.
- acae912 **feat: use `network-contacts` for prod environment**
If we are using a production network, the autonomi client should not provide an explicit peer and
instead use the network contacts. In production it's possible for the single peer to become
unavailable and this would then break the uploader.
We need to use a template to do this, so the file was moved to a jinja template.
- 55d66cf **feat: copy upload script on uploader upgrade**
If the script has been updated, the new version will be copied as part of the upgrade.
=> feat: use `network-contacts` for prod environment

src/ansible/provisioning.rs, src/bootstrap.rs, src/deploy.rs, src/funding.rs, src/lib.rs, src/main.rs, src/upscale.rs
Previously we were using the 'custom' network type for doing a deployment with Anvil, but what we actually need the custom case for is when we want to use a different token contracts address. This will still use Arbitrum Sepolia, it's just that it will use a different token address. However, the payment address and the RPC URL still need to be supplied with the command. This is a closer match to how the `custom` network type is used in the node manager.
As part of this commit, the counts for the Ansible banners were removed. They are not very useful and were difficult to maintain based on all the different options.
=> feat: differentiate 'custom' and anvil networks

resources/ansible/roles/telegraf-configuration/defaults/main.yml, src/lib.rs
For a while the network dashboard will also use an intermediate branch.
=> chore: use rc branch for network dashboard

src/main.rs
We now need to check `autonomi` rather than `safe_network`.
=> chore: update repo branch reference

resources/ansible/nodes.yml
It is sometimes possible that the application of the `node` role will result in an error, such as some nodes failing to start. In this case, Ansible will stop applying remaining roles on hosts where the failure occurred. For this reason, we want to configure and start Telegraf before we attempt to start the nodes, so that we will still collect monitoring data even if one or two nodes fail to start.
=> chore: apply `telegraf-configuration` role before `node` role

resources/ansible/roles/uploaders/templates/upload-random-data.sh.j2
It was recommended we use 100MB files to reduce gas fees.
The gas fee drain rate is also affected by the upload speed, so a sleep between each upload was also recommended.
I've also introduced a banner, which should help to differentiate between each upload when scrolling through the service log.
=> chore: increase uploaded file size and sleep

resources/ansible/start_uploaders.yml, resources/ansible/stop_uploaders.yml
Since there is a one-to-one mapping between an `antX` user and an uploader service, the number of uploader instances is determined by how many users there are.
=> feat: adapt start/stop uploaders for multi user setup

src/inventory.rs
The versioning output was changed for this binary.
=> fix: update version prefix for `ant` binary

resources/ansible/uploaders.yml
The service should now be started automatically rather than be in a stopped state, which was requested for development work.
=> fix: ensure telegraf is running on uploaders

resources/ansible/roles/cache_webserver/tasks/main.yml
This is necessary for for the monitoring setup.
=> fix: symlink the `nginx_status` file

resources/ansible/roles/genesis-node/tasks/main.yml, resources/ansible/roles/node/tasks/main.yml, resources/ansible/roles/uploaders/templates/ant_uploader.service.j2
- defc507 **fix: make network id optional**
The variable was not being correctly referenced in these tasks.
- ed4b838 **chore: prevent nodes not starting killing entire playbook**
In the case of the peer cache setup, if the nodes did not start correctly, the nginx playbook was
not being applied.
=> chore: prevent nodes not starting killing entire playbook

resources/ansible/roles/uploaders/templates/ant_uploader.service.j2
Without the newline in the template, the service definition was not written correctly.
=> fix: apply network id to uploader service

resources/terraform/testnet/digital-ocean/PROD-02.tfvars
This is going to be bootstrapped from the `PROD-01` environment. It will have the same size machines.
Since it's bootstrapped, the peer cache and uploaders don't apply, so those counts are set to 0.
=> chore: define spec for `prod-02` environment

resources/ansible/reset_to_n_nodes.yml, resources/ansible/roles/reset-to-n-nodes/tasks/main.yml, resources/ansible/roles/reset-to-n-nodes/templates/reset_to_n_nodes.sh.j2, resources/ansible/start_nodes.yml, resources/ansible/stop_nodes.yml, src/ansible/mod.rs, src/main.rs
- f6d8efe **chore: use `antctl` to start/stop nodes**
Replaces the old references to `safenode-manager`.
- ba4b097 **feat: provide `reset-to-n-nodes` command**
This command runs a playbook that uses a Bash script to clear out existing nodes then create the
specified number of new nodes.
It is intended to be used in the production environment to reset nodes for a particular environment,
to avoid having to bootstrap a new one.
In production, there will be intervals applied to the `stop` and `start` commands such that the
existing node services will be stopped gradually, and the new services will come online slowly,
probably with an interval of about 5 minutes between each.
=> feat: provide `reset-to-n-nodes` command

src/inventory.rs, src/lib.rs
In the case of our current production environment, I accidentally reset the node registry on the genesis VM, which meant that the inventory for the production environment could no longer be generated.
I since started 5 nodes on the genesis VM, so I'm just going to take the first node in the registry even if there are none with the `--first` flag.
It could also be possible that the original genesis VM was destroyed. So the inventory process treats it as optional.
=> feat: handle missing or altered genesis node

src/ansible/extra_vars.rs, src/bootstrap.rs, src/deploy.rs, src/infra.rs, src/inventory.rs, src/lib.rs, src/main.rs, src/upscale.rs
- 2133a2d **chore: remove remaining traces of network keys**
These were removed from `antnode` and are no longer required.
- ca32ee4 **chore: use different version retrieving mechanism**
The versions for both `antnode` and `antctl` can just come from a random VM rather than the node
registry.
- ca780ed **feat: support custom branch for upscale**
The upscale does not build the binaries. Instead it uses the build from the original deployment. The
binary option can be set to the same owner/branch reference as the previous deployment, and this
means Ansible will pick up the URL where the custom binary was uploaded to.
- 07ef86b **chore: remove redundant args from `upscale` cmd**
The `--desired-auditor-vm-count` and `--downloaders-count` arguments do not apply any more.
- 5ae4436 **refactor: …
=> feat: support custom branch for upscale

src/deploy.rs
This should be true by default, because the only case in which private nodes are not provisioned is if the user explicitly sets the count to 0.
=> fix: use correct default value for nat gateway setup

resources/ansible/nodes.yml
If we have say 2 VMs, failure in 1 vm would result in 50% failure and the whole workbook would fail. 
We ignore the failures inside the rust code anyway, so I feel like we could atleast let the playbooks keep executing even if 1 vm fails.
=> fix: do not fail on errors

Cargo.lock, src/funding.rs
This version has a change for increasing the timeouts on some types of transactions, which should be helpful because I had some timeouts when trying to upscale the prod uploaders.
I also made a couple of basic changes to the funding process:
* It prints out more text that was previously only available with debug-level logging. This output is actually useful because it can take a while to transfer funds to the wallets.
* Changed some of the variable names, which I think helped make the code a bit more readable.
=> chore: update to evmlib 0.1.8

src/main.rs, src/upscale.rs
The uploader provisioning should only run when either of the uploader counts have been supplied.
This prevents the need to supply the secret key for the funding wallet on other types of upscales where it is not relevant.
=> chore: provision uploaders on upscale when specified

resources/ansible/roles/private_node/tasks/main.yml
- Swap out use of ip cli to netplan cli in order to have the ip route rules survive reboots and networkd services restarts
Please mark the types of changes made in this pull request.
Please ensure all of the following tasks have been completed:
=> feat: switch from ip cli to netplan cli

resources/ansible/roles/telegraf-configuration/tasks/main.yml, resources/ansible/roles/telegraf-geoip/tasks/main.yml
Sometimes these services randomly fail to start.
=> chore: apply retries to telegraf service starts

src/ansible/provisioning.rs, src/deploy.rs, src/main.rs, src/upscale.rs
It could be useful to do this as part of the deployment rather than also having an additional funding run later.
Plus, it could be set to 0 on the initial deploy if need be.
=> feat: specify gas and token amounts on `deploy`

resources/ansible/roles/telegraf-configuration/tasks/main.yml
This sometimes fails randomly. I didn't notice it before because the task name had been mislabelled.
=> chore: retry telegraf-elasticsearch restart

src/cmd/deployments.rs, src/cmd/funds.rs, src/cmd/logs.rs, src/cmd/misc.rs, src/cmd/mod.rs, src/cmd/network.rs, src/cmd/nodes.rs, src/cmd/telegraf.rs, src/cmd/upgrade.rs, src/cmd/uploaders.rs, src/lib.rs, src/main.rs
- 0fffc67 **refactor: split command management into modules**
The enormous `main` module was becoming very unwieldy and was difficult for AI to digest.
This splits the command handling into different modules.
A few things were removed in this refactor:
* Duplicate `DeployOptions` struct
* The `faucet` subcommand
* The `logstash` subcommand
A few functions have a Clippy suppression for too many arguments: it's not worth breaking these
arguments into an options struct.
=> refactor: split command management into modules

src/inventory.rs, src/lib.rs
The current command only incorporated the symmetric private nodes.
=> feat: accommodate new private node setup in `status` cmd

resources/ansible/start_uploaders.yml, resources/ansible/stop_uploaders.yml
For the first time ever, I caught an error during one of the deploys when trying to stop the uploader service.
Now applying a retry.
=> chore: retry on start/stop uploader services

src/ansible/provisioning.rs, src/inventory.rs
I didn't realise, but these private node types also need to be supported.
Also don't print either types of private nodes in the inventory if they are not present.
=> fix: restore provisioning private nodes

.github/workflows/merge.yml, resources/ansible/stop_nodes.yml, src/ansible/provisioning.rs, src/cmd/mod.rs, src/cmd/nodes.rs, src/lib.rs, src/main.rs
Enables individual services to be stopped rather than all of them.
=> feat: provide `--service-name` arg on `stop` cmd

resources/terraform/testnet/digital-ocean/dev.tfvars, resources/terraform/testnet/digital-ocean/staging.tfvars
In the development and staging setups we will not use full cone NAT until we are doing more experimentation and testing with that configuration.
=> chore: do not use full cone nat by default

resources/ansible/roles/genesis-node/defaults/main.yml, resources/ansible/roles/node/defaults/main.yml, resources/ansible/roles/node/tasks/main.yml, src/ansible/extra_vars.rs, src/ansible/provisioning.rs
The upcoming release of `antctl` has changed the `--home-network` flag to `--relay`.
=> refactor: rename `--home-network` to `--relay`

resources/ansible/roles/genesis-node/tasks/main.yml, resources/ansible/roles/node/tasks/main.yml
The `antctl` binary now adds the `--upnp` flag by default, so we have to explicitly switch it off for the deployment of the node on droplets.
=> chore: use `--no-upnp` flag for node services

resources/ansible/genesis_node.yml, resources/ansible/nodes.yml, resources/ansible/peer_cache_node.yml, resources/ansible/roles/setup_striped_storage/defaults/main.yml, resources/ansible/roles/setup_striped_storage/tasks/main.yml, resources/ansible/roles/uploaders/defaults/main.yml, resources/ansible/roles/uploaders/tasks/main.yml, resources/ansible/roles/uploaders/templates/upload-random-data.sh.j2, resources/ansible/uploaders.yml, resources/terraform/testnet/digital-ocean/main.tf, resources/terraform/testnet/digital-ocean/variables.tf
- d741e1b **chore: vary base mount point for striped volume**
I want to use this role to mount a volume on the uploaders too, so the base mount point may be
different.
I renamed the role to something a bit more specific that I think captures the purpose.
I've also taken out a role being applied to the playbook that formatted a disk if we were using AWS
as the provider. We will hopefully move to AWS soon, but for the time being this was causing a bit
of confusion and I don't think it will be used; we'll probably need the striped volume setup for AWS
too.
- ed609e7 **chore: apply retries for service restarts**
I've seen these fail during deployments and unfortunately they will cause the workflow run to fail.
A simple restart should prevent the failure. These have been applied to other …
=> feat: use additional volume for upload logs

src/ansible/provisioning.rs, src/bootstrap.rs, src/cmd/deployments.rs, src/cmd/mod.rs
It's better to just assert that the network ID is required rather than leaving it optional, because it will inevitably be forgotten. If we want to bootstrap from `mainnet`, we can just explicitly use 1 as the ID.
=> feat: `bootstrap` cmd requires `--network-id` arg

resources/ansible/build.yml
The construct being used before this was recursive and did not work correctly.
=> fix: correctly evaluate binaries to build

src/inventory.rs
I'm trying to get the Telegraf config on the production environment upgraded to point to the new ELK instance, so I'm trying to make the inventory backwards compatible. It should be OK if we don't have any clients.
=> feat: support no clients in inventory

src/ansible/extra_vars.rs
These runs for upgrading the Telegraf configuration need to have the `enable_telegraf` variable set.
=> fix: pass `enable_telegraf` flag

resources/ansible/roles/node/defaults/main.yml, resources/ansible/roles/node/tasks/main.yml, src/ansible/extra_vars.rs, src/ansible/provisioning.rs
- Nodes behind full cone nat gateways are equivalent to port forwarded nodes, and hence they don't require the `--relay` flag.
=> feat: do not set relay flag for full cone nats

src/deploy.rs, src/funding.rs
- Running `deploy` cmd on a failed deployment would not provision client vms. This should fix that now.
=> fix: client provisioning is now idempotent

src/inventory.rs
The previous check for an empty inventory was that there were at least some nodes on generic and peer-cache hosts.
However, now we have certain test configurations where we don't want any nodes on generic or peer-cache hosts, so we'll just check for the existence of a genesis node.
=> chore: relax determination of empty inventory

resources/ansible/roles/downloaders/defaults/main.yml, resources/ansible/roles/downloaders/tasks/main.yml, resources/ansible/roles/downloaders/templates/ant_downloader.sh.j2, resources/ansible/roles/uploaders/defaults/main.yml
The new CLN branch seems to have much more verbose logging, which caused the disks to fill up on the client machines, since the downloaders were never setup to log to the alternate locations.
We can address the logging output, but in principle it's just good for the logs for the downloaders to also go to the external disk.
=> feat: downloaders log to external disk

src/inventory.rs
The bootstrap deployment is not going to have a genesis node to work with, so we can use generic node hosts in this case.
=> fix: determine empty inventory for bootstrap deployment

resources/ansible/upgrade_clients.yml
The client upgrade playbook was missing several things since the uploader configuration had moved on a bit.
=> fix: bring client upgrade playbook up to speed

resources/ansible/roles/downloaders/templates/ant_downloader.sh.j2
The `ant` binary prints the file address on both successful and failed downloads, so we can have it printed once rather than three times. This will reduce a lot of noise in the service log.
=> chore: reduce file references in service log

resources/ansible/roles/uploaders/templates/ant_random_uploader.sh.j2
For tests against the production network it will be more helpful if we only stop processing on successful uploads, since quite a lot of the time our uploads can fail due to gas price fluctuations.
=> chore: use successful uploads for max uploads

CLAUDE.md, Cargo.lock, Cargo.toml, resources/ansible/roles/cache_webserver/tasks/main.yml, resources/ansible/roles/cache_webserver/templates/nginx.conf.j2, resources/ansible/roles/genesis-node/tasks/main.yml, resources/ansible/roles/node/defaults/main.yml, resources/ansible/roles/node/tasks/main.yml, resources/ansible/roles/uploaders/templates/ant_random_uploader.sh.j2, resources/ansible/upgrade_nginx.yml, resources/ansible/upgrade_nodes.yml, src/ansible/extra_vars.rs, src/ansible/inventory.rs, src/ansible/mod.rs, src/ansible/provisioning.rs, src/cmd/clients.rs, src/cmd/deployments.rs, src/cmd/mod.rs, src/cmd/nginx.rs, src/cmd/provision.rs, src/cmd/upgrade.rs, src/digital_ocean.rs, src/inventory.rs, src/lib.rs, src/logs.rs, src/main.rs, src/s3.rs, src/setup.rs, src/ssh.rs, src/terraform.rs
- The nginx server now serves caches based on the passed in `Cache-Version` header.
- If `Cache-Version` is absent, i.e, the case with old antnodes, we'd return version0.
- If `Cache-Version` is 1, we serve the latest version.
- For anyother case, we return an error.
- 7de9027 **feat: ngnix serves cache file based on header**
- ca11015 **fix(nginx): update the nginx config file to support multiple cache version**
- 02fc723 **fix: set default value for write_older_cache_files**
- e3ede67 **chore: clippy fixes**
- e0b6f4d **chore: add config file for working with claude code**
This was generated using Claude itself.
I haven't modified it initially because I'm not too familiar with things yet.
- f8f9753 **feat: provide `nginx upgrade-config` command**
This will be used to upgrade the …
=> feat: ngnix serves cache file based on header

resources/ansible/roles/build_safe_network_binary/tasks/main.yml, src/ansible/extra_vars.rs, src/ansible/inventory.rs, src/ansible/provisioning.rs, src/cmd/clients.rs, src/cmd/deployments.rs, src/cmd/mod.rs, src/cmd/provision.rs, src/digital_ocean.rs, src/inventory.rs, src/lib.rs, src/logs.rs, src/s3.rs, src/setup.rs, src/ssh.rs, src/terraform.rs
There can sometimes be files (like `Cargo.lock`) that get modified when a binary is built in the previous application of this role. The `force` parameter should deal with this situation without causing a failure.
=> chore: allow modifications on `autonomi` repo

resources/ansible/upgrade_clients.yml
On the client upgrade, we can also provide newer versions of the downloader script.
I'm not sure why this wasn't added before.
=> chore: upgrade the downloader script

CLAUDE.md, resources/ansible/roles/cache_webserver/tasks/main.yml, resources/ansible/roles/cache_webserver/templates/nginx.conf.j2, resources/ansible/roles/genesis-node/tasks/main.yml, resources/ansible/roles/node/defaults/main.yml, resources/ansible/roles/node/tasks/main.yml, resources/ansible/upgrade_nginx.yml, resources/ansible/upgrade_nodes.yml, src/ansible/extra_vars.rs, src/ansible/mod.rs, src/ansible/provisioning.rs, src/cmd/mod.rs, src/cmd/nginx.rs, src/cmd/upgrade.rs, src/lib.rs, src/main.rs
- f59f109 **chore: use successful uploads for max uploads**
For tests against the production network it will be more helpful if we only stop processing on
successful uploads, since quite a lot of the time our uploads can fail due to gas price fluctuations.
- e77d53f **chore(release): 0.2.72**
- 2fb30b1 **feat: ngnix serves cache file based on header**
- bf07b96 **fix(nginx): update the nginx config file to support multiple cache version**
- 20bab15 **fix: set default value for write_older_cache_files**
- 68f5e39 **chore: clippy fixes**
- a91f427 **chore: add config file for working with claude code**
This was generated using Claude itself.
I haven't modified it initially because I'm not too familiar with things yet.
- 68f1071 **feat: provide `nginx upgrade-config` command**
This will be …
=> Support FIFO Cache

resources/terraform/clients/digital-ocean/dev-images-lon1.tfvars, resources/terraform/clients/digital-ocean/production-images-lon1.tfvars, resources/terraform/clients/digital-ocean/staging-images-lon1.tfvars, resources/terraform/clients/digital-ocean/variables.tf
The client deployment should use the same build image as the testnet deployment, so rather than having a default value, it will also be supplied from tfvars.
=> chore: supply build image from variable files

resources/ansible/roles/static-downloaders/templates/ant_static_downloader.sh.j2
For these performance and testing scenarios we need to have the cache disabled so we are downloading from fresh start on errors.
=> feat: disable cache on file download

resources/ansible/roles/uploaders/templates/ant_random_uploader.sh.j2
The output of `ant` will now be written to the service log as it executes.
This is very useful for long-running uploads.
=> feat: file upload output in service log

src/infra.rs
The absence of this meant the UPnP setup was not being customised properly.
=> fix: supply upnp vm count to terraform run

resources/terraform/testnet/digital-ocean/PROD-01.tfvars
This would replace the current setup we have on large `s-8vcpu-16gb` VMs with a smaller `s-2vcpu-4gb` setup.
=> chore: new spec for a production environment

src/bootstrap.rs
This should really have been done when the command was originally extended.
=> fix: provision upnp nodes in the `bootstrap` command

.github/workflows/merge.yml, Justfile
This can be used to avoid compilation when using `testnet-deploy` in a workflow.
=> chore: build a `testnet-deploy` package

Cargo.lock, src/infra.rs
For port restricted hosts, the count variable variable was only being applied if its count was greater than 0, causing the default value of 1 to be used.
Also removes the use of a Terraform variable that was not being used.
=> fix: apply vm count even with zero value

src/inventory.rs
The port restricted VMs were using a different enum variant from the symmetric and full cone NAT VMs in the inventory generation process. This resulted in errors when port restricted VMs were disabled.
=> fix: use correct enum variant for node type
